export const OPEN_DRAWER = "OPEN_DRAWER";
export const CLOSE_DRAWER = "CLOSE_DRAWER";

export const OPEN_CREATE_EXPENSE_MODAL = "OPEN_CREATE_EXPENSE_MODAL";
export const CLOSE_CREATE_EXPENSE_MODAL = "CLOSE_CREATE_EXPENSE_MODAL";

export const GET_EXPENSES_LIST = "GET_EXPENSES_LIST";
export const GET_EXPENSES_LIST_SUCCESS = "GET_EXPENSES_LIST_SUCCESS";
export const GET_EXPENSES_LIST_FAIL = "GET_EXPENSES_LIST_FAIL";

export const CREATE_EXPENSE = "CREATE_EXPENSE";
export const CREATE_EXPENSE_SUCCESS = "CREATE_EXPENSE_SUCCESS";
export const CREATE_EXPENSE_FAIL = "CREATE_EXPENSE_FAIL";
