export const OPEN_DRAWER = "OPEN_DRAWER";
export const CLOSE_DRAWER = "CLOSE_DRAWER";

export const OPEN_CREATE_CALCULATION_MODAL = "OPEN_CREATE_CALCULATION_MODAL";
export const CLOSE_CREATE_CALCULATION_MODAL = "CLOSE_CREATE_CALCULATION_MODAL";

export const GET_CALCULATIONS_LIST = "GET_CALCULATIONS_LIST";
export const GET_CALCULATIONS_LIST_SUCCESS = "GET_CALCULATIONS_LIST_SUCCESS";
export const GET_CALCULATIONS_LIST_FAIL = "GET_CALCULATIONS_LIST_FAIL";

export const CREATE_CALCULATION = "CREATE_CALCULATION";
export const CREATE_CALCULATION_SUCCESS = "CREATE_CALCULATION_SUCCESS";
export const CREATE_CALCULATION_FAIL = "CREATE_CALCULATION_FAIL";

export const GET_ALL_DATA = "GET_ALL_DATA";

export const GET_CALCULATION = "GET_CALCULATION";
export const GET_CALCULATION_SUCCESS = "GET_CALCULATION_SUCCESS";
export const GET_CALCULATION_FAIL = "GET_CALCULATION_FAIL";
export const ADD_EXPENSE = "ADD_EXPENSE";
export const UPDATE_EXPENSE = "UPDATE_EXPENSE";
export const DELETE_EXPENSE = "DELETE_EXPENSE";

export const GET_CARDS = "GET_CARDS";
export const GET_CARDS_SUCCESS = "GET_CARDS_SUCCESSS";
export const GET_CARDS_FAIL = "GET_CARDS_FAIL";

export const GET_PERSONS = "GET_PERSONS";
export const GET_PERSONS_SUCCESS = "GET_PERSONS_SUCCESS";
export const GET_PERSONS_FAIL = "GET_PERSONS_FAIL";
